### ISSUE TITLE
Customizing the TimelineItem middle element

### ISSUE THREAD

**Issue by SalahAdDin** [pk12/material-timeline#1]
It is not such a big thing, but... I have a requirement to modify the padding and border for this [middle](https://github.com/pk12/material-timeline/blob/5414918460e78cfc3ab2b16451af03da60bd4cd5/src/lib/TimelineItem/TimelineItem.js#L74) element to:
```
		timelineYear: {
			alignSelf: 'flex-start',
			padding: '0 12px',
borderRadius: '50%',
			backgroundColor: props => props.yearBackgroundColor,
			color: props => props.yearColor,
		},
```

Could be possible to make them as a `props` too, or maybe the class itself to be overridden?

Thanks.

**Comment by pkanellidis** [comment]
Yes, it can be extended, will do so tomorrow.
