### ISSUE TITLE
Feature: split header/label, for each item

### ISSUE THREAD

**Issue by SalahAdDin** [pk12/material-timeline#4]
Hi, i found an interesting feature for the timeline in [Ant.Desing](https://ant.design/components/timeline/): 
![image](https://user-images.githubusercontent.com/5034215/79501963-9df72d80-8037-11ea-8aeb-9895759fd6db.png)

Separate header(in its case, date from content) from the content we can put both in the same line and not just in one of the two sides.

What do you think about it?

**Comment by pkanellidis** [comment]
This could be done by creating a new TimelineItem (e.g. FullTimelineItem with header/date on the left/right, the item wrapper in the middle could be provided as props and finally the card/body) as Timeline itself is a wrapper.

**Comment by SalahAdDin** [comment]
@pk12 can you make an example?
