### ISSUE TITLE
cardMedia component should be optional

### ISSUE THREAD

**Issue by SalahAdDin** [pk12/material-timeline#8]
Hello, I'm trying to put the card headers in at beginning of the margin but I find a problem doing it:
![image](https://user-images.githubusercontent.com/5034215/79864965-08ff8600-83e3-11ea-97c7-6667c472eb9e.png)
We are not using the card media component and it is still being rendering, for this reason it is giving "left padding"  that can't be avoided.

A solution is deleting it, but it should be optional, I think.

Thanks.

**Comment by pkanellidis** [comment]
@SalahAdDin It's true, fixing it now

**Comment by pkanellidis** [comment]
Published version 1.0.4 that should fix it
